name: DoNothing Release

on:
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@dont-push-symbols-on-release
    with:
      workdir: Frends.TestTask.DoNothing
    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
      