name: DoNothing Release
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/official_task_pipeline.yml@hot-fix
    with:
      workflow_mode: release
      os: all
      workdir: Frends.TestTask.DoNothing
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      target_feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}