name: DoNothing Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.TestTask.DoNothing/**'
      - '.github/workflows/**'
  workflow_dispatch:


jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/collective_build.yml@workflows-update
    with:
      os: lin
      dotnet_version: 6.0.x
      workdir: Frends.TestTask.DoNothing
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_vars: '{"username": ${{ toJSON(secrets.USERNAME) }}}'