name: DoNothing Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.TestTask.DoNothing/**'
  workflow_dispatch:
  
jobs:
  linux_build:
    name: build on linux
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.TestTask.DoNothing
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
  windows_build:
    name: build on windows
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.TestTask.DoNothing
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}