name: DoNothing Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.TestTask.DoNothing/**'
  workflow_dispatch:
  

jobs:
  linux_build:
    name: build on Ubuntu
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test_partner.yml@fspw-320
    with:
      workdir: Frends.TestTask.DoNothing